var url = window.location;
// url = url.host + url.pathname + url.hash;
// console.log(url)
angular.module("sngs").factory("config", function() {
    return {
        identification: "Connexion",
        home: "Ventes",
        appNameShort: "SNG-S",
        appNameFull: "SONGO-STOCK",
        appSlogan: "Perenniser votre activite..!",
        appVersion: "5.8",
        structBenef: "ETYF INTERNATIONAL",
        contact: "70 66 59 54 / 79 78 35 79 /  62 58 00 93",
        email: "contact@tongogroup.com",
        serverUrl: url.pathname + "/app/core/",
        appUrl: url.pathname + "/app/",
        urlLogin: "/login",
        urlHome: "/home",
        urlParamCat: "/prmcat",
        urlParamEditCat: "/prmecat/:objectID",
        urlParamUnit: "/prmunit",
        urlParamEditUnit: "/prmeunit/:objectID",
        urlParamBank: "/prmbnk",
        urlParamEditBank: "/prmbnk/:objectID",
        urlParamArt: "/prmart",
        urlParamEditArtt: "/prmeart/:objectID",
        urlParamMag: "/prmmag",
        urlParamEditMag: "/prmemag/:objectID",
        urlParamTd: "/prmtd",
        urlParamEditTd: "/prmetd/:objectID",
        urlParamClt: "/prmclt",
        urlParamEditClt: "/prmeclt/:objectID",
        urlParamFrns: "/prmfrns",
        urlParamEditFrns: "/prmefrns/:objectID",
        urlParamCusr: "/prmcusr/",
        urlParamEditCusr: "/prmecusr/:objectID",
        urlParamAccess: "/prmaccess/",
        urlParamEditAccess: "/prmaccess/:objectID",
        urlStockBa: "/stkba",
        urlStockBcmd: "/stkbcmd",
        urlStockEditBa: "/stkba/:objectID",
        urlStockAs: "/stkas",
        urlStockBs: "/stkbs",
        urlStockEditBs: "/stkbs/:objectID",
        urlStockSs: "/stkss",
        mdlS: "s.php?x=",
        mdlFrontContrl: "frontController.php?x=",
        mdlParamCat: "categorie.class.php?x=",
        mdlParamUnit: "unite.class.php?x=",
        mdlParamAdmin: "administration.class.php?x=",
        mdlParamBank: "banque.class.php?x=",
        mdlParamTd: "typeDepense.class.php?x=",
        mdlParamArt: "article.class.php?x=",
        mdlParamMag: "magasin.class.php?x=",
        mdlParamCusr: "user.class.php?x=",
        mdlParamStruct: "structure.class.php?x=",
        mdlParamOpt: "configs.class.php?x=",
        mdlParamClt: "client.class.php?x=",
        mdlParamFrns: "fournisseur.class.php?x=",
        mdlParamUsrs: "utilisateur.class.php?x=",
        mdlStockBa: "approvisionnement.class.php?x=",
        mdlStockAs: "approvisionnement.class.php?x=",
        mdlStockCmd: "commande.class.php?x=",
        mdlStockBcmd: "commande.class.php?x=",
        mdlStockBs: "sortie.class.php?x=",
        mdlStockSs: "sortie.class.php?x=",
        mdlStockStk: "stock.class.php?x=",
        mdlDeff: "deffectueux.class.php?x=",
        mdlTransfert: "transfert.class.php?x=",
        mdlVente: "vente.class.php?x=",
        mdlReglement: "reglement.class.php?x=",
        mdlEtat: "etat.class.php?x=",
        mdlDecaiss: "decaissement.class.php?x=",
        mdlAnnul: "annulation.class.php?x=",
        timeout: 0,
        INTERVAL_VNT_JOUR: 30000,
        INTERVAL_VNT_RPT_VNT_JOUR: 110000,
        INTERVAL_VNT_RPT_RPT_JOUR: 70000,
        INTERVAL_ETAT_CRCE: 80000,
        INTERVAL_ETAT_DETTE: 80000,
        INTERVAL_ETAT_GRT: 80000,
        INTERVAL_ETAT_CAIS_JOUR: 80000,
        INTERVAL_ETAT_CAIS_DATE: 80000,
        INTERVAL_ETAT_VAL_STK: 80000,
        INTERVAL_ALERTES: 50000,
        CACHE_RECYCLE_FREQ: 1000,
        CACHE_MAX_AGE: 7200000,
        CACHE_FLUSH_INTERVAL: 7200000,
        CACHE_DELETE_ON_EXPIRE: "aggressive",
        waitingTimeBeforeTask: 1000
    }
});